// Mocks generated by Mockito 5.4.2 from annotations
// in ui_rendering_app/test/features/presentation/bloc/get_rendering_json_bloc_test/rendering_json_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:bloc/bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ui_rendering_app/features/domain/usecases/rendering_json_usecase.dart'
    as _i2;
import 'package:ui_rendering_app/features/presentation/bloc/get_rendering_json_bloc/rendering_json_bloc.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRenderingJsonUseCase_0 extends _i1.SmartFake
    implements _i2.RenderingJsonUseCase {
  _FakeRenderingJsonUseCase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRenderingJsonState_1 extends _i1.SmartFake
    implements _i3.RenderingJsonState {
  _FakeRenderingJsonState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetRenderingJsonBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRenderingJsonBloc extends _i1.Mock
    implements _i3.GetRenderingJsonBloc {
  @override
  _i2.RenderingJsonUseCase get getRenderingJsonUseCase => (super.noSuchMethod(
        Invocation.getter(#getRenderingJsonUseCase),
        returnValue: _FakeRenderingJsonUseCase_0(
          this,
          Invocation.getter(#getRenderingJsonUseCase),
        ),
        returnValueForMissingStub: _FakeRenderingJsonUseCase_0(
          this,
          Invocation.getter(#getRenderingJsonUseCase),
        ),
      ) as _i2.RenderingJsonUseCase);

  @override
  _i3.RenderingJsonState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeRenderingJsonState_1(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeRenderingJsonState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.RenderingJsonState);

  @override
  _i4.Stream<_i3.RenderingJsonState> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<_i3.RenderingJsonState>.empty(),
        returnValueForMissingStub: _i4.Stream<_i3.RenderingJsonState>.empty(),
      ) as _i4.Stream<_i3.RenderingJsonState>);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void add(_i3.RenderingJsonEvent? event) => super.noSuchMethod(
        Invocation.method(
          #add,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onEvent(_i3.RenderingJsonEvent? event) => super.noSuchMethod(
        Invocation.method(
          #onEvent,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void emit(_i3.RenderingJsonState? state) => super.noSuchMethod(
        Invocation.method(
          #emit,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void on<E extends _i3.RenderingJsonEvent>(
    _i5.EventHandler<E, _i3.RenderingJsonState>? handler, {
    _i5.EventTransformer<E>? transformer,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #on,
          [handler],
          {#transformer: transformer},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onTransition(
          _i5.Transition<_i3.RenderingJsonEvent, _i3.RenderingJsonState>?
              transition) =>
      super.noSuchMethod(
        Invocation.method(
          #onTransition,
          [transition],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void onChange(_i5.Change<_i3.RenderingJsonState>? change) =>
      super.noSuchMethod(
        Invocation.method(
          #onChange,
          [change],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #addError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onError(
    Object? error,
    StackTrace? stackTrace,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #onError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
